#!/bin/sh
#
# main lemonbar
# depends on https://github.com/stark/siji
#
# wm script

a="%{F#D4B0AF}"
t="%{F-}"
fifo=/tmp/bar

# source all functions
for i in ~/lemonbar/lemons/*; do
    . "$i"
done

# ensure proper script cleanup
trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$fifo" ] && rm "$fifo"
mkfifo "$fifo"

wks > "$fifo" &
clk > "$fifo" &
ntw > "$fifo" &
vol > "$fifo" &
bat > "$fifo" &

while read -r line; do
    case $line in
        W*) wks=${line#?};;
        C*) clk=${line#?};;
        N*) ntw=${line#?};;
        V*) vol=${line#?};;
        B*) bat=${line#?}
    esac

    echo "%{l}  ${wks} %{r}${ntw} ${clk} ${vol}  ${bat}  "
done < "$fifo" | \
    lemonbar -g x30 \
    -f "scientifica:size=9" \
    -f "Wuncon Siji:size=9" \
    -B \#382122 \
    -F \#ede3e0
